//
//  NewsFeedModels.swift
//  VK-client
//
//  Created by Artem Firsov on 10/28/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsFeed
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        enum RequestType {
            case some
            case getFeed
            case getNewsFeed
        }
    }
    struct Response
    {
        enum ResponseType {
            case some
            case presentNewsFeed(feed: NewsResponse)
//            case presentNewsFeed(feedResponse: FeedViewModel)
        }
    }
    struct ViewModel
    {
        enum ViewModelData {
            case some
            case displayNewsFeed(feedViewModel: FeedViewModel)
        }
    }
  }
}

struct FeedViewModel {
    struct Cell: FeedCellViewModel {
        var avatarImageUrl: String
        var name: String
        var date: String
        var postText: String?
        var likes: String?
        var views: String?
        var comments: String?
        var shares: String?
        var postImage: FeedCellPostImage?
        var sizes: FeedCellSizes
    }
    
    
    
    struct PostImageViewModel: FeedCellPostImage {
        var postPhotoUrl: String?
        var width: Int
        var height: Int
    }
    
    
    
    let cells: [Cell]
}
